const pagesActionTypes = {
  FETCH_PAGES_START: 'FETCH_PAGES_START',
  FETCH_PAGES_SUCCESS: 'FETCH_PAGES_SUCCESS',
  FETCH_FAILURE: 'FETCH_FAILURE',
  FETCH_SINGLE_PAGE_START: 'FETCH_SINGLE_PAGE_START',
  FETCH_SINGLE_PAGE_SUCCESS: 'FETCH_SINGLE_PAGE_SUCCESS',
  DELETE_PAGE_SUCCESS: 'DELETE_PAGE_SUCCESS',
  ADD_PAGE_SUCCESS: 'ADD_PAGE_SUCCESS',
  SET_SUCCESS_MESSAGE: 'SET_SUCCESS_MESSAGE',
  SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
  CLEAR_MESSAGE: 'CLEAR_MESSAGE'
};

export default pagesActionTypes;
